apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: enterprisecontractpolicy-sample
spec:
  description: My custom enterprise contract policy configuration
  sources:
    - name: Policies object
      policy:
        - quay.io/hacbs-contract/ec-release-policy:latest
  exceptions: # Deprecated. Use configuration as seen below
    nonBlocking: # Deprecated. Use excludeRules as seen below
      - not_useful
      - test:conftest-clair
  configuration:
    exclude:
      - not_useful
      - test:conftest-clair
    include:
      - always_checked
    collections:
      - salsa_one_collection
